name: .NET CI/CD Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore throw-exception-alternative/throw-exception-alternative/throw-exception-alternative.csproj

    - name: Build project
      run: dotnet build throw-exception-alternative/throw-exception-alternative/throw-exception-alternative.csproj --no-restore --configuration Release

    - name: Run tests (if any)
      run: dotnet test throw-exception-alternative/throw-exception-alternative/throw-exception-alternative.csproj --no-build --configuration Release --verbosity normal
      continue-on-error: true

    - name: Publish artifacts
      run: dotnet publish throw-exception-alternative/throw-exception-alternative/throw-exception-alternative.csproj --no-build --configuration Release --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app-${{ github.sha }}
        path: ./publish
        retention-days: 30

  code-quality:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore throw-exception-alternative/throw-exception-alternative/throw-exception-alternative.csproj

    - name: Build with warnings as errors
      run: dotnet build throw-exception-alternative/throw-exception-alternative/throw-exception-alternative.csproj --no-restore --configuration Release --verbosity normal

    - name: Run static analysis
      run: |
        echo "Static analysis would run here"
        echo "Consider adding tools like SonarQube, CodeQL, or other analyzers"

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore throw-exception-alternative/throw-exception-alternative/throw-exception-alternative.csproj

    - name: Security vulnerability scan
      run: |
        echo "Security scan would run here"
        echo "Consider adding tools like Snyk, OWASP dependency check, or GitHub security scanning"
